In [1]:
%load_ext autoreload
%autoreload 2

In [51]:
import torch
inputs = torch.load('../condqa_old/data/dev_inputs', map_location='cpu')

In [68]:
inputs[3][-1].nonzero()


tensor([[111,   0,   1],
        [192,   0,   1]])

In [57]:
ans_indicator = torch.tensor([[[1, 0, 0], [0, 0, 1]], [[0, 1, 0], [1, 0, 0]]])#1, 2, 3
cond_indicator = torch.tensor([[[0, 1, 1], [1, 1, 0]], [[1, 1, 1], [0, 0, 0]]])
cond_indicator = cond_indicator.unsqueeze(2).repeat(1, 1, 3, 1)# 1, 2, 3, 3
cond_indicator = torch.einsum('abcd,abc->acd',cond_indicator, ans_indicator)


In [60]:
A = torch.tensor([[1, 1, 0]])
torch.einsum('ab,ac->abc',A, A)

tensor([[[1, 1, 0],
         [1, 1, 0],
         [0, 0, 0]]])

In [36]:
print([i['has_answer'] for i in examples[25]['document'] if i['has_answer'] != -1])


[3, 0, 1, 2, 0, 1, 2]


In [21]:
set(inputs[6][5].flatten().tolist())


{-1.0, 0.0, 1.0}

In [25]:
inputs[6][7][inputs[6][7]!=0]

tensor([1, 1, 1, 1, 1, 1])

In [31]:
for i in range(len(inputs)):
    for j in [1, 2, 3, 7]:
        inputs[i][j] = inputs[i][j].bool()

In [39]:
from utils import ReIndexer
indexer = ReIndexer()
hiddens = torch.arange(40).reshape(2, 10, 2)
mask = torch.rand(2, 10) > 0.8
mask = mask.float()
indexer.set_index(mask)
new_hiddens, new_mask = indexer.re_index(hiddens)


In [45]:
recovered_hiddens = 

tensor([[4, 0, 1, 2, 3, 5, 6, 7, 8, 9],
        [1, 5, 0, 2, 3, 4, 6, 7, 8, 9]])

In [49]:
recovered_hiddens = torch.empty_like(first_indexer.index.unsqueeze(-1).repeat(1, 1, 2)).scatter_(dim=1, index=first_indexer.index.unsqueeze(-1).repeat(1, 1, 2), src=new_hiddens)

In [30]:
from utils import convert_examples_to_inputs, Tokenizer
tokenizer = Tokenizer('../condqa_old/model')
inputs = convert_examples_to_inputs(examples, tokenizer)

converting examples to inputs..: 100%|██████████| 352/352 [00:01<00:00, 182.42it/s]


In [32]:
torch.save(inputs, '../condqa_old/data/dev_inputs')

In [33]:
for i in inputs[0]:
    print(i.dtype, i.shape)

torch.int64 torch.Size([4000])
torch.bool torch.Size([4000])
torch.bool torch.Size([4000])
torch.bool torch.Size([4000])
torch.float32 torch.Size([4000, 3])
torch.float32 torch.Size([4000, 2])
torch.int64 torch.Size([])
torch.bool torch.Size([4000, 5, 2])


In [4]:
inputs = torch.load('../condqa_old/data/dev_inputs')

In [55]:
inputs[38][-2]

tensor(29)

In [59]:
inputs[39][-1].nonzero()


tensor([[ 969,    0,    1],
        [1142,    0,    0]])